export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const CLEAR_FORGET_PASSWORD_ALERT = 'CLEAR_FORGET_PASSWORD_ALERT';
export const SET_FORGET_PASSWORD_ALERT = 'SET_FORGET_PASSWORD_ALERT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_DIAGNOSIS = 'ADD_DIAGNOSIS';
export const HIDE_DIAGNOSIS_RESULT = 'HIDE_DIAGNOSIS_RESULT';
export const FLAG_MESSAGE = 'FLAG_MESSAGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const IS_BOT_THINKING = 'IS_BOT_THINKING';

export const GET_NOTES = 'GET_NOTES';
export const SEND_NOTES_ERROR = 'SEND_NOTES_ERROR';
export const SAVE_NOTE = 'SAVE_NOTE';

export const GET_CASES = 'GET_CASES';
export const GET_CASE_INFO = 'GET_CASE_INFO';
export const APPEND_CHAT_MESSAGE = 'APPEND_CHAT_MESSAGE';

export const SET_USER_TYPE = 'SET_USER_TYPE';

export const SEARCH_MAP = 'SEARCH_MAP';
export const CLEAR_SEARCH = 'CLEAR_SEARCH_MAP_RESULTS';

export const SORT_BY_FEE = "SORT_BY_FEE";
export const SORT_BY_FEE_DESC = "SORT_BY_FEE_DESCENDING";
export const CLASS_SELECTED = "CLASS_ADDED_TO_FILTERS";
export const SUBJECT_SELECTED = "SUBJECT_ADDED_TO_FILTERS";
export const EXPERIENCE_SELECTED = "EXPERIENCE_SELECTED";
export const GENDER_SELECTED = "GENDER_SELECTED";
export const FEE_RANGE_SELECTED = "FEE_RANGE_SELECTED";
export const SEARCH_QUERY = "SEARCH_TEXT";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_NUM_TEACHERS = "CHANGE_TECHERS_COUNT_PAGE";
export const LOAD_DATA = "LOAD_DATA";
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const LOAD_DATA_FAILED = "LOAD_DATA_FAILED";

//Map constants
export const UPDATE_TEXTINPUT = 'UPDATE_TEXTINPUT_MAP'
export const RECEIVE_GEOCODE_RESULTS = 'RECEIVE_GEOCODE_RESULTS'
export const RECEIVE_GEO_RESULTS = 'RECEIVE_FILTERED_GEO_RESULTS_TEACHERS'
export const REQUEST_GEOCODE_RESULTS = 'REQUEST_GEOCODE_RESULTS'
export const UPDATE_CENTER = 'UPDATE_CENTER_MAP'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS_MAP'
